// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs_f4bcXxmkW2Pc_hopu6O6I-FpSDz9yU',
    appId: '1:379096163474:web:388d046ee4078e6e4d324b',
    messagingSenderId: '379096163474',
    projectId: 'project-app-3b585',
    authDomain: 'project-app-3b585.firebaseapp.com',
    storageBucket: 'project-app-3b585.firebasestorage.app',
    measurementId: 'G-H9WP18C194',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrO3pr8tZjVyYwODFGyXFQrztcPY5bMms',
    appId: '1:379096163474:android:066412591eb515134d324b',
    messagingSenderId: '379096163474',
    projectId: 'project-app-3b585',
    storageBucket: 'project-app-3b585.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGX1DILUO6-uPXnTGOKHKrSSjPGOJh0rw',
    appId: '1:379096163474:ios:d41d7866b48958684d324b',
    messagingSenderId: '379096163474',
    projectId: 'project-app-3b585',
    storageBucket: 'project-app-3b585.firebasestorage.app',
    androidClientId: '379096163474-3f1vvbjmv7itsqv6278hrslqb321mpjk.apps.googleusercontent.com',
    iosClientId: '379096163474-05gbollgnbivh100nunvfmaf8ohfchqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGX1DILUO6-uPXnTGOKHKrSSjPGOJh0rw',
    appId: '1:379096163474:ios:d41d7866b48958684d324b',
    messagingSenderId: '379096163474',
    projectId: 'project-app-3b585',
    storageBucket: 'project-app-3b585.firebasestorage.app',
    androidClientId: '379096163474-3f1vvbjmv7itsqv6278hrslqb321mpjk.apps.googleusercontent.com',
    iosClientId: '379096163474-05gbollgnbivh100nunvfmaf8ohfchqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs_f4bcXxmkW2Pc_hopu6O6I-FpSDz9yU',
    appId: '1:379096163474:web:623aa77121a83e6b4d324b',
    messagingSenderId: '379096163474',
    projectId: 'project-app-3b585',
    authDomain: 'project-app-3b585.firebaseapp.com',
    storageBucket: 'project-app-3b585.firebasestorage.app',
    measurementId: 'G-3WGQBJSWT1',
  );
}
